version: '3.9'

networks:
  dev_network:

services:
  redis_db:
    image: redis:7-alpine
    restart: always
    env_file:
      - ${ENV}
    ports:
      - 6380:6379
    networks:
      dev_network:
        aliases:
          - redis
