"""prices table

Revision ID: 1c1426ae84ee
Revises: f3fbb541920c
Create Date: 2024-01-27 16:25:09.570855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1426ae84ee'
down_revision = 'f3fbb541920c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('tko', sa.Float(precision=12), nullable=True),
    sa.Column('maintenance_common', sa.Float(precision=12), nullable=True),
    sa.Column('drainage_common', sa.Float(precision=12), nullable=True),
    sa.Column('cold_water_common', sa.Float(precision=12), nullable=True),
    sa.Column('hot_water_volume_common', sa.Float(precision=12), nullable=True),
    sa.Column('hot_water_energy_common', sa.Float(precision=12), nullable=True),
    sa.Column('electricity_common', sa.Float(precision=12), nullable=True),
    sa.Column('heating', sa.Float(precision=12), nullable=True),
    sa.Column('cold_water', sa.Float(precision=12), nullable=True),
    sa.Column('hot_water_volume', sa.Float(precision=12), nullable=True),
    sa.Column('hot_water_energy', sa.Float(precision=12), nullable=True),
    sa.Column('drainage', sa.Float(precision=12), nullable=True),
    sa.Column('gas', sa.Float(precision=12), nullable=True),
    sa.Column('renovation', sa.Float(precision=12), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prices_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_reg_at'), ['reg_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_reg_at'))

    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prices_created_at'))

    op.drop_table('prices')
    # ### end Alembic commands ###
